spring.application.name=soporte

server.port=8080

spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.jsmmgntfrzngqhhioxba
spring.datasource.password=$4/JaNp-LpP8N.w

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false
gemini.api.key=${GEMINI_API_KEY}
gemini.model=gemini-2.5-flash